import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import TopNavbar from "component-nest/components/client/navbars/TopNavbar";
import TextLink from "component-nest/components/client/links/TextLink";
import { useRouter } from "next/navigation";
import { useUser } from "@auth0/nextjs-auth0/client";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let { user, error, isLoading } = useUser();
  const router = useRouter();

  return (
    <html className="dark" lang="en">
      <title>Ourkive</title>
      <UserProvider>
        <body className={inter.className}>
          <TopNavbar>
            <TextLink
              onClick={() =>
                router.push(`/api/auth/${user ? "logout" : "login"}`)
              }
            >
              {user ? "Logout" : "Login"}
            </TextLink>
          </TopNavbar>
          {children}
        </body>
      </UserProvider>
    </html>
  );
}
