import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import Navbar from "./components/navbar";
import UserDataProvider from "./provider/userDataProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <title>Ourkive</title>
      {/* Wrap the application in our custom user provider */}
      <UserDataProvider>
        {/* Wrap the application in the Auth0 provider for authentication  */}
        <UserProvider>
          <body>
            <Navbar></Navbar>
            {children}
          </body>
        </UserProvider>
      </UserDataProvider>
    </html>
  );
}
