import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import Navbar from "./components/navbar";
import UserProfileProvider from "./provider/userProfileProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="text-light-font-color-1 dark:text-dark-font-color-1"
    >
      <title>Ourkive</title>
      {/* Wrap the application in our custom user provider */}
      <UserProfileProvider>
        {/* Wrap the application in the Auth0 provider for authentication  */}
        <UserProvider>
          <body className={inter.className}>
            <Navbar></Navbar>
            {children}
          </body>
        </UserProvider>
      </UserProfileProvider>
    </html>
  );
}
